databases:
  - name: todo-db
    plan: free
    databaseName: todo
    user: todo_user

services:
  - type: web
    name: todo-aghirculesei
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGINS
        value: '["https://todo-frontend-aghirculesei.onrender.com"]'
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString

  - type: web
    name: todo-frontend-aghirculesei
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://todo-aghirculesei.onrender.com
